#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
# echo "from django.contrib.auth.models import User; User.objects.create_superuser('${DJ_ADMIN_NAME}', 'admin@example.com', '${DJ_ADMIN_PW}')" | python manage.py shell
python manage.py runserver 0.0.0.0:8000
