version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: mapclub_core
    container_name: mapclub_core
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./compose/local/django/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: mapclub_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mapclub
      - POSTGRES_PASSWORD=mapclub
      - POSTGRES_DB=mapclub_dev

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./compose/local/django/.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./compose/local/django/.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./compose/local/django/.env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
