version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    container_name: mapclub_core
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./compose/production/django/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: mapclub_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./compose/production/django/.env.db
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    container_name: mapclub_nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:7-alpine
  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./compose/production/django/.env
    depends_on:
      - redis
      - db
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./compose/production/django/.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: django_celery_example_celery_flower
    command: /start-flower
    volumes:
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./compose/production/django/.env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:

