version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: mapclub_core
    container_name: mapclub_core
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./compose/local/django/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: mapclub_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mapclub
      - POSTGRES_PASSWORD=mapclub
      - POSTGRES_DB=mapclub_dev

volumes:
  postgres_data:
