# Generated by Django 4.1.5 on 2023-02-17 16:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to=map.models.get_upload_path)),
                ("slug", models.SlugField()),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to=map.models.get_thumbnail_path
                    ),
                ),
                (
                    "deepzoom",
                    models.FileField(
                        blank=True, null=True, upload_to=map.models.get_deepzoom_path
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("pub_date", models.DateField(default=datetime.datetime.today)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maps",
                        to="map.category",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_modifiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_added",),
            },
        ),
    ]
